### ISSUE TITLE
 Элемент списка НЕ выглядит в соответствии с предоставленными макетами дизайна.

### ISSUE THREAD

**Issue by POlinOcHcka** [5ir1us/android-diplom#132]
Иконка вакансии отображается поверх контейнера-скругления
![Image](https://github.com/user-attachments/assets/dd5a7740-8ff1-4c8c-9a79-8700ada99e4a)
![Image](https://github.com/user-attachments/assets/283d4a5d-a754-42a4-ad88-29b77624b551)

**Comment by ypypyxa** [comment]
Иконка вакансии отображается поверх контейнера-скругления
